server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone:
        http://eureka7001:7001/eureka/  #和7001互相注册，其中“eureka7001”为host文件中定义的127.0.0.1的别名