server:
  port: 8001

spring:
  application:
    name: springcloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/yanchong?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: yanchong

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yanchong.springcloud.entities       #所有Entity别名类所在包

logging:
  level:
    com:
      yanchong:
        springcloud:
          dao: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:
        http://eureka7001:7001/eureka,http://eureka7002:7002/eureka  #集群版
  instance:
    appname: payment